# Generated by Django 2.1.2 on 2020-02-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletest', '0002_article_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(default='defo', upload_to='documents/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
